import { z } from "zod";

/** Stable machine-readable codes returned in tRPC `error.data.apiCode`. */
export const API_ERROR_CODES = {
  FORM_NOT_FOUND: "FORM_NOT_FOUND",
  FORM_NOT_PUBLISHED: "FORM_NOT_PUBLISHED",
  FORM_FORBIDDEN: "FORM_FORBIDDEN",
  FORM_FIELD_NOT_FOUND: "FORM_FIELD_NOT_FOUND",
  RESPONSE_NOT_FOUND: "RESPONSE_NOT_FOUND",
  FORM_NOT_ACCEPTING_RESPONSES: "FORM_NOT_ACCEPTING_RESPONSES",
  FORM_SLUG_CONFLICT: "FORM_SLUG_CONFLICT",
  FORM_FIELD_LABEL_KEY_CONFLICT: "FORM_FIELD_LABEL_KEY_CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UPDATE_REQUIRES_FIELDS: "UPDATE_REQUIRES_FIELDS",
  AUTH_CONFLICT: "AUTH_CONFLICT",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const apiErrorCodeModel = z.enum([
  API_ERROR_CODES.FORM_NOT_FOUND,
  API_ERROR_CODES.FORM_NOT_PUBLISHED,
  API_ERROR_CODES.FORM_FORBIDDEN,
  API_ERROR_CODES.FORM_FIELD_NOT_FOUND,
  API_ERROR_CODES.RESPONSE_NOT_FOUND,
  API_ERROR_CODES.FORM_NOT_ACCEPTING_RESPONSES,
  API_ERROR_CODES.FORM_SLUG_CONFLICT,
  API_ERROR_CODES.FORM_FIELD_LABEL_KEY_CONFLICT,
  API_ERROR_CODES.VALIDATION_ERROR,
  API_ERROR_CODES.UPDATE_REQUIRES_FIELDS,
  API_ERROR_CODES.AUTH_CONFLICT,
  API_ERROR_CODES.AUTH_INVALID_CREDENTIALS,
  API_ERROR_CODES.RATE_LIMIT_EXCEEDED,
  API_ERROR_CODES.INTERNAL_ERROR,
]);

export const apiErrorDataModel = z.object({
  apiCode: apiErrorCodeModel.describe("Application error code"),
});

export type ApiErrorData = z.infer<typeof apiErrorDataModel>;
